const prefixArq = 'arq';
const prefixDc = 'dc';

export const categoryModel = {
    DC_CREATOR: `${prefixDc}.creator`,
    DC_TITLE: `${prefixDc}.title`,
    DC_DATE: `${prefixDc}.date`,
    ARQ_NOMBRE: `${prefixArq}.Nombre`,
    ARQ_DIRECCION: `${prefixArq}.Direccion`,
    ARQ_PERTENENCIA: `${prefixArq}.Pertenencia`,
    ARQ_LOCALIDAD: `${prefixArq}.Localidad`,
    ARQ_MUNICIPIO: `${prefixArq}.Municipio`,
    ARQ_ENTIDAD: `${prefixArq}.Entidad`,
    ARQ_JURISDICCION: `${prefixArq}.Jurisdiccion`,
    ARQ_CATEGORIAACTUAL: `${prefixArq}.CategoriaActual`,
    ARQ_CATEGORIAORIGINAL: `${prefixArq}.CategoriaOriginal`,
    ARQ_EPOCA: `${prefixArq}.Epoca`,
    ARQ_ANIO: `${prefixArq}.Anio`,
    ARQ_USOACTUAL: `${prefixArq}.UsoActual`,
    ARQ_FUNDADOR: `${prefixArq}.Fundador`,
    ARQ_CONSTRUCTOR: `${prefixArq}.Constructor`,
    ARQ_ESTADOCONSERVACION: `${prefixArq}.EstadoConservacion`,
    ARQ_TIPOLOGIA: `${prefixArq}.Tipologia`,
    ARQ_TIPOLOGIAARQUI: `${prefixArq}.TipologiaArqui`,
    ARQ_MUROS: `${prefixArq}.Muros`,
    ARQ_SISTEMACUBIERTA: `${prefixArq}.SistemaCubierta`,
    ARQ_SISESTRUCTNAVE: `${prefixArq}.SisEstructNave`,
    ARQ_SISESTRUCTCRUCERO: `${prefixArq}.SisEstructCrucero`,
    ARQ_SISESTRUCTPRESBITERIO: `${prefixArq}.SisEstructPresbiterio`,
    ARQ_SISESTRUCTCORO: `${prefixArq}.SisEstructCoro`,
    ARQ_PISOS: `${prefixArq}.Pisos`,
    ARQ_ACABADOS: `${prefixArq}.Acabados`,
    ARQ_MATERIALES: `${prefixArq}.Materiales`,
    ARQ_GALLINASCIEGAS: `${prefixArq}.GallinasCiegas`,
    ARQ_BIENES: `${prefixArq}.Bienes`,
    ARQ_OBSERVBienes: `${prefixArq}.ObservBienes`,
    ARQ_OBSERVGENERALES: `${prefixArq}.ObservGenerales`,
    ARQ_SEARCHSTRING: `${prefixArq}.SearchString`
};
