const prefixArq = 'arq  ';
const prefixDc = 'dc';

export const excelCategory = {
    nombre: { excel: 'Nombre', dspace: `${prefixArq}Nombre` },
    direccion: {excel:'Dirección',dspace:`${prefixArq}Direccion`},
    pertence: {excel:'Pertenece a',dspace:`${prefixArq}Direccion`},
    localidad: {excel:'Localidad',dspace:`${prefixArq}Direccion`},
    municipio: {excel:'Municipio',dspace:`${prefixArq}Direccion`},
    entidad: {excel:'Entidad',dspace:`${prefixArq}Direccion`},
    jurisdiccionEclesiasticaFundacion: {excel:'Jurisdiccion eclesiastica de su fundacion',dspace:`${prefixArq}Direccion`},
    categoriaActual:{excel:'Categoria actual',dspace:`${prefixArq}Direccion`},
    categoriaOriginal: {excel:'Categoría original',dspace:`${prefixArq}Direccion`},
    epocaConstruccion: {excel:'Epoca de construcción',dspace:`${prefixArq}Direccion`},
    anioConstruccion: {excel:'Año de construcción y fechas significativas',dspace:`${prefixArq}Direccion`},
    usoActual: {excel:'usoActual',dspace:`${prefixArq}Direccion`},
    fundador: {excel:'fundador',dspace:`${prefixArq}Direccion`},
    constructor: {excel:'constructor',dspace:`${prefixArq}Direccion`},
    estadoConservacion:{excel:'Estado de conservación',dspace:`${prefixArq}Direccion`},
    tipologia:{excel:'Tipología',dspace:`${prefixArq}Direccion`},
    tipologiaArquitectonicaIglesias:{excel:'Tipología arquitectónica de las iglesias',dspace:`${prefixArq}Direccion`},
    muros:{excel:'muros',dspace:`${prefixArq}Direccion`},
    sistemaCubiertaOriginal:{excel:'Sistema de cubierta original',dspace:`${prefixArq}Direccion`},
    sistemaEstructuralPresbiterio:{excel:'Sistema estructural del presbiterio',dspace:`${prefixArq}Direccion`},
    sistemaEstructuralCoro:{excel:'Sistema estructural del coro',dspace:`${prefixArq}Direccion`},
    pisos:{excel:'pisos',dspace:`${prefixArq}Direccion`},
    acabados:{excel:'acabados',dspace:`${prefixArq}Direccion`},
    materiales:{excel:'materiales',dspace:`${prefixArq}Direccion`},
    gallinasCiegas:{excel:'Gallinas ciegas',dspace:`${prefixArq}Direccion`},
    bienesMueblesElementosSignificativosRelevantes:{excel:'Bienes muebles y elementos significativos relevantes',dspace:`${prefixArq}Direccion`},
    observacionesBienesMueblesElementosSignificativosRelevantes:{excel:'Observaciones de bienes muebles y elementos significativos relevantes',dspace:`${prefixArq}Direccion`},
    observacionesGenerales:{excel:'Observaciones generales',dspace:`${prefixArq}Direccion`},
}